--subqueries
SELECT 

    B1.B1_COD,
    B1.B1_DESC,

    (
        SELECT MAX(D2.D2_EMISSAO)
        FROM SD2010 D2
        WHERE D2.D2_FILIAL = '09ALFA01' AND D2.D2_DOC = B1.B1_COD AND D2.D2_TIPO NOT IN('B','D') AND D2.D_E_L_E_T_=''

    ) AS ULT_VENDA,

    (
        SELECT MAX(D1.D1_DTDIGIT)
        FROM SD1010 D1
        WHERE D1.D1_FILIAL = '09ALFA01' AND D1.D1_COD = B1.B1_COD AND D1.D1_TIPO NOT IN('B','D') AND D1.D_E_L_E_T_=''
    ) AS ULT_COMPRA


FROM SB1010 B1

WHERE B1.B1_FILIAL = '09ALFA'

AND B1.D_E_L_E_T_=''